BAH 2962 | System user and templates
Bahmni/clinic-config pull request #206
Opened 2023-07-03 06:09 UTC by atish160384

Templates for appointment sms and registration sms and a system user with privilege of send sms added

2023-07-03 11:28 UTC, gsluthra commented on masterdata/configuration/liquibase/liquibase.xml
> +    <changeSet id="BAH-2962-20230629" author="Anubhav" runAlways="true">
author should be "Bahmni" for all liquibase changesets.

2023-07-03 11:28 UTC, gsluthra commented on masterdata/configuration/liquibase/liquibase.xml
> +        <sql>
There is no "check" for when to run. And it says, runAlways.. which means this insert will get added on each run?

2023-07-03 11:30 UTC, gsluthra commented on masterdata/configuration/liquibase/liquibase.xml
> +            INSERT INTO provider (person_id, identifier, creator, date_created, uuid, name) VALUES (@person_id, 'systemuser', 1, now(), uuid(), 'SystemUser');
can we instead call the user: `system-user`

2023-07-04 06:46 UTC, gsluthra approved these changes

2023-07-11 09:48 UTC, rahu1ramesh approved these changes

2023-08-11 09:09 UTC, angshu commented on masterdata/configuration/roles/roles.csv
> +7e8bd096-da70-11ec-9d64-0242ac120002,FrontDesk,"User have ability to login and perform front desk operations(search patient, register patient etc)",Provider;Lab;Appointments:FullAccess,Edit Users;Get
where are you creating these privileges? I hope they are defined in config.xml of individual omods?

2023-08-11 09:09 UTC, angshu approved these changes

2023-08-11 09:32 UTC, gsluthra requested changes
Please incorporate comments discussed today. Users dont need privilege for SMS sending, since this is a system feature. When this feature is ON, the SMS MUST go, irrespective of who the user is.

2023-09-14 09:32 UTC, atish160384 commented
Sure Gurpreet will remove the creation of new roles and privillages as discussed other code will remain the same .Changes are now moved to a new PR.

2023-09-14 09:32 UTC, closed without merging