BAH-3024 | Sort columns in the Clinical Queue tabular view
Bahmni/clinic-config pull request #244
Opened 2024-04-18 05:03 UTC by Arjun-Go

JIRA - https://bahmni.atlassian.net/browse/BAH-3024

# Summary

As part of this card, we are handling how columns in clinical tabular view can be hidden and how we can choose those columns that can be set as an identifier completely through configuration.

2024-04-18 05:27 UTC, rahu1ramesh commented
Thanks @Arjun-Go for the PR. Could you also please document the same in our Bahmni Wiki for future reference?

2024-04-19 05:45 UTC, parvathy00 approved these changes

2024-04-20 08:55 UTC, rahu1ramesh approved these changes

2024-04-24 01:38 UTC, rahu1ramesh requested changes

2024-04-24 01:38 UTC, rahu1ramesh commented on openmrs/apps/clinical/app.json
> +        "ignoredTabularViewHeadings": ["display", "uuid", "image", "activeVisitUuid", "hasBeenAdmitted", "programUuid", "enrollment"],
| OT Screen | Radiology Screen | Orders Screen | Bed Management Screen |
|-----------------------|-----------------------|-----------------------|-----------------------|
| ![Screenshot 2024-04-23 at 9 38 16 PM](https://github.com/Bahmni/default-config/assets/121226043/602bdef2-6352-4ff8-bfd8-1152d5195937) | ![Screenshot 2024-04-23 at 9 39 50 PM](https://github.com/Bahmni/default-config/assets/121226043/9f0f9ce7-4126-49ad-855f-ad5e0756f42d) | ![Screenshot 2024-04-23 at 9 43 40 PM](https://github.com/Bahmni/default-config/assets/121226043/a36dbf66-3f26-4d16-b6a6-4b19f64c80fc) | ![Screenshot 2024-04-23 at 9 47 02 PM](https://github.com/Bahmni/default-config/assets/121226043/0038e0d7-b5d1-4615-ba9b-8c6aab8b47ae) |

The sort logic for patient search is used across Bahmni on screens that support patient search. The following configuration is to be added to these screens to specify which columns to ignore or how to identify the identifier heading. 

Note that some values in the arrays below may not be relevant to the clinical/app settings and should be added to the other app.json file.

2024-04-24 10:41 UTC, rahu1ramesh approved these changes

2024-04-24 12:43 UTC, merged